package EnumerationTypes;

public enum ErrorType {
    SEMICOLON,
    PROGRAM,
    END,
    LEFTCOMMENT,
    RIGHTCOMMENT,
    LEFTBRAC,
    RIGHTBRAC,
    LOOP,
    EXTRASTATEMENT,
    STATEMENT_ERROR,
    STATEMENT_INVALID_ASSIGNMENT_ERROR,
    UNDECLARED_ERROR,
    FLOAT_NUMBER,
    VARIABLE_NAME,
    INVALID_CHAR
}